### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nltk_english.txt'

### ISSUE THREAD

**Issue by chetansb77** [HKUST-KnowComp/Pronoun-Coref-KG#1]
Hi,
I'm getting this error when I'm trying to run "./setup_conll_data.sh".
Where can I get this file?

Here is the error log

mv: cannot move 'reference-coreference-scorers' to 'conll-2012/scorer/reference-coreference-scorers': Directory not empty
----------------------------------------------------------------------------------------------------

could not find the gold parse [/projects/WebWare6/ontonotes-release-5.0/data/files/data/arabic/annotations/nw/ann/01/ann_0103.parse] in the ontonotes distribution ... exiting ...

----------------------------------------------------------------------------------------------------
cat: 'conll-2012/v4/data/development/data/english/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/train/data/english/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/test/data/english/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/development/data/chinese/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/train/data/chinese/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/test/data/chinese/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/development/data/arabic/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/train/data/arabic/annotations/*/*/*/*.v4_gold_conll': No such file or directory
cat: 'conll-2012/v4/data/test/data/arabic/annotations/*/*/*/*.v4_gold_conll': No such file or directory
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "minimize.py", line 13, in <module>
    import util
  File "/content/Pronoun-Coref-KG/util.py", line 414, in <module>
    with open('nltk_english.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'nltk_english.txt'
Traceback (most recent call last):
  File "get_char_vocab.py", line 25, in <module>
    get_char_vocab_language("english")
  File "get_char_vocab.py", line 23, in get_char_vocab_language
    get_char_vocab(["{}.{}.jsonlines".format(partition, language) for partition in ("train", "dev", "test")], "char_vocab.{}.txt".format(language))
  File "get_char_vocab.py", line 11, in get_char_vocab
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'train.english.jsonlines'
Traceback (most recent call last):
  File "filter_embeddings.py", line 14, in <module>
    with open(json_filename) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'train.english.jsonlines'

**Comment by panda0881** [comment]
Hi, the nltk_english file has been uploaded. It is just a stop words list.
