### ISSUE TITLE
Predicting on new text.

### ISSUE THREAD

**Issue by spiritbreake** [HKUST-KnowComp/Pronoun-Coref-KG#2]
How can I get model predictions on my custom dataset? 

There is Evaluate_Pronoun.py but I think it gives us performance numbers on a standard dataset where we have labels. I want to get predictions of this model on my custom dataset.

Any help regarding this is highly appreciated.

Thanks!

**Comment by panda0881** [comment]
Hi,

You can first change your dataset into the standard format and then create a new function called prediction in the pronoun_coref_kg_model.py. As you can see from the test function of our model, l.987 actually predicts the positions of all noun phrases that our model treates as the correct antecedent.

You should be able to get the predictions out from that line.

Best Regards,
Hongming
